version: '3.4'

services:
  duber.invoice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
      - ConnectionStrings__InvoiceDB=${AZURE_INVOICE_DB:-Server=sql.data;Database=Duber.InvoiceDb;User Id=sa;Password=Pass@word}      
      - ConnectionStrings__AppConfig=${AZURE_APP_CONFIG:-}      
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - PaymentServiceBaseUrl=${PAYMENT_SERVICE_URL:-http://externalsystem.payment}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
      - ChaosApiSettings__BaseUrl=${CHAOS_SERVICE_URL:-http://duber.chaos.api}
    ports:
      - "32776:80"

  duber.trip.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
      - EventStoreConfiguration__ConnectionString=${AZURE_TRIP_DB:-mongodb://nosql.data}
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
      - ChaosApiSettings__BaseUrl=${CHAOS_SERVICE_URL:-http://duber.chaos.api}
      - ConnectionStrings__AppConfig=${AZURE_APP_CONFIG:-}      
    ports:
      - "32775:80"

  duber.chaos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
      - ConnectionStrings__ChaosDB=${AZURE_CHAOS_DB:-}      
      - ConnectionStrings__AppConfig=${AZURE_APP_CONFIG:-}      
    ports:
      - "32778:80"

  duber.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
      - ConnectionStrings__WebsiteDB=${AZURE_WEBSITE_DB:-Server=sql.data;Database=Duber.WebSiteDb;User Id=sa;Password=Pass@word}      
      - ConnectionStrings__AppConfig=${AZURE_APP_CONFIG:-}      
      - EventBusConnection=${AZURE_SERVICE_BUS:-rabbitmq}
      - TripApiSettings__BaseUrl=${TRIP_SERVICE_BASE_URL:-http://duber.trip.api}
      - AzureServiceBusEnabled=${SERVICE_BUS_ENABLED:-False}
      - ChaosApiSettings__BaseUrl=${CHAOS_SERVICE_URL:-http://duber.chaos.api}
    ports:
      - "32774:80"

  sql.data:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  externalsystem.payment:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT:-Production}
    ports:
      - "32777:80"

